services:
  - type: web
    name: dash_project
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn dash_project.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: dash_project.settings
      - key: PYTHON_VERSION
        value: 3.12.6
